# Generated by Django 4.2.7 on 2023-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
