# Generated by Django 4.2.7 on 2023-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_earning_description_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
