# Generated by Django 4.2.7 on 2023-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_expense_invoice_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
